spring:
  application:
    name: iim

  datasource:
    url: jdbc:mysql://localhost:3306/iim_db?createDatabaseIfNotExist=true
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL@gmail.com
    password: YOUR_GMAIL_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-location: file:///C:/QrImages/
jwt:
  secret: YOUR_JWT_SECRET_KEY
  expiration: 10800000
